# Track Enemy Tool Configuration File

[General]
screen_width=1920
screen_height=1080
cs2_path=C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive
update_frequency_ms=20

[Memory]
offsets_folder=memory-offsets
memory_mode=
physmem_path=
directory_table_base=
physical_memory_file=
client_base=